### PR TITLE
Fix height to height of viewport and make logs scrollable

### PR DESCRIPTION
**Pull request by lucianjon**

### CODE REVIEW

**Comment by lucianjon** [comment]
Fixes height of elements so everything fits in the view port. Also makes the log container scrollable to avoid scrolling the entire page when there's lot's of log messages.

**Comment by marianogappa** [comment]
@lucianjon Just want to show you that the title bar is centered originally and your change de-centers it. Can you find a solution for that please? Then it looks mergeable 📦:
screen shot 2016-05-02 at 1 18 26 pm

**Comment by lucianjon** [comment]
@MarianoGappa: fixed with dffbac71550f01edaefac65fd50c9f914c2811ff

screen shot 2016-05-02 at 1 38 19 pm

**Comment by marianogappa** [comment]
@lucianjon: LGTM; on a 9:16 ratio screen like the one I'm writing this on now, 10% of the vh is gonna be too much for the title, but I think your solution is better than what I have now.

**Pull request merged**
